-- FALTAN SP --
-- REABRIR - CERRAR - RECHAZAR

-- FALTAN VIEW -- 
-- TICKETS CERRADOS - ABIERTOS - EN ANALISIS - POR CADA EMPRESA - POR CADA OPERADOR

-- TRIGGER --
-- REGISTROS DE CAMBIOS EN LOS TICKETS -- 

